spring:
  application.name: hub-router
  main:
    log-startup-info: false
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  config.import:
    - "classpath:hub-router.yaml"
    - "classpath:stage.yaml"

logging:
  level:
    org.springframework.context: ERROR
    org.apache.kafka: ERROR
    net.devh: ERROR
    ru.yandex.practicum.telemetry: ERROR