server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3

collector:
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1
