<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ru.yandex.practicum</groupId>
        <artifactId>serialization</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>avro-schemas</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.apache.avro</groupId>
            <artifactId>avro</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-avro-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>schema</goal>
                        </goals>
                        <configuration>
                            <sourceDirectory>${project.basedir}/src/main/avro</sourceDirectory>
                            <outputDirectory>${project.build.directory}/generated-sources/avro</outputDirectory>
                            <stringType>String</stringType>
                            <createSetters>true</createSetters>
                            <fieldVisibility>PRIVATE</fieldVisibility>
                            <imports>
                                <import>${project.basedir}/src/main/avro/DeviceTypeAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/ConditionTypeAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/ConditionOperationAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/ActionTypeAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/DeviceAddedEventAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/DeviceRemovedEventAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/ScenarioConditionAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/DeviceActionAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/ScenarioAddedEventAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/ScenarioRemovedEventAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/ClimateSensorAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/LightSensorAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/MotionSensorAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/SwitchSensorAvro.avsc</import>
                                <import>${project.basedir}/src/main/avro/TemperatureSensorAvro.avsc</import>
                            </imports>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/avro</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
