spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 50
    producer:
      acks: all
      retries: 3

aggregator:
  kafka:
    poll-timeout: 1s
    topics:
      sensors: telemetry.sensors.v1
      snapshots: telemetry.snapshots.v1
      partitions: 1
      replicas: 1
